SELECT NOW(), CURDATE(), CURTIME();
SELECT YEAR(NOW()), MONTH(NOW()),DAY(NOW()),HOUR(NOW()), SECOND(NOW()), SECOND(NOW());
SELECT DAYNAME(NOW()), MONTHNAME(NOW());
SELECT EXTRACT(DAY FROM NOW());
SELECT DATE_FORMAT(NOW(), '%y-%Y-%m-%M-%d-%D-%H:%i %p');
SELECT DATE_ADD(NOW(), INTERVAL 1 day);
SELECT DATE_SUB(NOW(), INTERVAL 1 day);
SELECT DATEDIFF('2020-06-16', '2020-05-16');
SELECT TIME_TO_SEC('01:29');
SELECT TIME_TO_SEC('01:40')- TIME_TO_SEC('01:29');

USE sql_store;
SELECT *
FROM orders
WHERE YEAR(order_date) >= YEAR(NOW());
